apiVersion: v1
kind: Pod
metadata:
  name: saya0
  labels:
    run: mypod
spec:
  containers:
  - image: sayali063/week4
    name: week4
    ports:
    - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  